export const GET_PAGES = 'GET_PAGES';
export const GET_PAGE = 'GET_PAGE';
export const GET_SITE = 'GET_SITE';

export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_INPUT_PASSWORD = 'USER_INPUT_PASSWORD';

export const TOGGLE_MODAL_POST = 'TOGGLE_MODAL_POST';
export const CHANGE_MODAL_POST = 'CHANGE_MODAL_POST';
export const SAVE_MODAL_POST = 'SAVE_MODAL_POST';

export const TOGGLE_MODAL_PAGE = 'TOGGLE_MODAL_PAGE';
export const CREATE_MODAL_PAGE = 'CREATE_MODAL_PAGE';
export const CHANGE_MODAL_PAGE = 'CHANGE_MODAL_PAGE';
export const SAVE_MODAL_PAGE = 'SAVE_MODAL_PAGE';
export const DELETE_MODAL_PAGE = 'DELETE_MODAL_PAGE';

export const TOGGLE_MODAL_PASS = 'TOGGLE_MODAL_PASS';
export const CHANGE_MODAL_PASS = 'CHANGE_MODAL_PASS';
export const RESET_MODAL_PASS = 'RESET_MODAL_PASS';

export const SAVE_SITE_SETTINGS = 'SAVE_SITE_SETTINGS';
export const CHANGE_SITE_SETTINGS = 'CHANGE_SITE_SETTINGS';

export const ERROR = 'ERROR';
export const ERROR_REMOVE = 'ERROR_REMOVE';

export const TOGGLE_MODAL_PHOTO = 'TOGGLE_MODAL_PHOTO';
export const LOAD_MODAL_PHOTO = 'LOAD_MODAL_PHOTO';
export const UPLOAD_MODAL_PHOTO = 'UPLOAD_MODAL_PHOTO';
export const DELETE_MODAL_PHOTO = 'DELETE_MODAL_PHOTO';
export const TOGGLE_LOAD_MODAL_PHOTO = 'TOGGLE_LOAD_MODAL_PHOTO';

export const TOGGLE_MENU = 'TOGGLE_MENU';

/* ---- SET ID ---- */
export const SITE_ID = '5a5facc5765eac14c49a008e';
